### ISSUE TITLE
How do you create nested "components" ?

### ISSUE THREAD

**Issue by MangelMaxime** [flimflamjs/ff-core#8]
Hello,

I am experimenting around FlimFlam and I want to create nested "components".
In this following [repo](https://github.com/MangelMaxime/FlimFlam-Showcase) you can see a "components" [**counter**](https://github.com/MangelMaxime/FlimFlam-Showcase/blob/master/Source/pages/samples/simple/counter.js) and another [**nested counter**](https://github.com/MangelMaxime/FlimFlam-Showcase/blob/master/Source/pages/samples/medium/nested_counter.js).

When using the **counter** component alone everything is working fine. I can add, reset etc.

Problem is coming, when using the **nested counter** components. Here I can add a new counter by clicking "Add a new counter" the change is reflected directly. However, if I click on the add button of one of the added counter no visual change is shown.
One way to force the display update, is to add a new counter, or delete one.

Here is a gif showing the problem.
![flimflamjs_nested_counter](https://cloud.githubusercontent.com/assets/4760796/21752795/07db7438-d5df-11e6-8308-cc1eaefaad47.gif)

My guess, is that at I don't implement the nested data correctly at this [line](https://github.com/MangelMaxime/FlimFlam-Showcase/blob/master/Source/pages/samples/medium/nested_counter.js#L7) 
and so the render don't discovered them for watch.

What is the recommanded way to work with nested components ?

**Comment by jayrbolton** [comment]
Please see this implementation of the multi-counter example:
* Source: https://github.com/jayrbolton/ff-example-multi-counters/blob/master/index.js
* Demo: http://jayrbolton.github.io/ff-example-multi-counters

I'm not sure if we ever need to dynamically initialize components --- I think this is a bit Object-Oriented thinking. I think some logic wuld have to be added to `flimflam-render` have to accommodate this sort of thing.

**Comment by jayrbolton** [comment]
I will read the code you have tonight as well to see how you're doing things

**Comment by jayrbolton** [comment]
On further thought, the issue here is dynamically creating and listening to new streams within the state object that were not present at the time the `render` function was initially called.

One solution would be to find all the new streams in the state object on every stream update, but I'm not sure what the implementation would be and what the performance impact would be. 

I do think you could make any UI without dynamically adding new streams, but also I think it could be convenient to dynamically initialize an arbitrary number of child components as the user interacts with the page. So I think we should support this.

This issue has been moved to the `flimflam-render` repo, which is responsible for the `render` function: https://github.com/jayrbolton/flimflam-render/issues/1

**Comment by MangelMaxime** [comment]
You would want the application to generate the whole application at once.

How would you create the counter list so ? 
Or for a more real case application: Create a list of tags with a close button. By tag I mean something like [that](http://bulma.io/documentation/elements/tag/)

Just curious to know your way to do it :)

**Comment by jayrbolton** [comment]
Not entirely sure I understand your comment, but this is how I'd do it:

```js
function init() {
  const tags$ = flyd.stream([]) // will contain array of tag names
  const [addTag$, removeTag$] = [stream(), stream()]
  const tags$ = flyd.scanMerge([
    [addTag$,  (tags, t) => R.append(t, tags)]
  , [removeTag$, (tags, idx) => R.remove(idx, 1, tags)]
  ], [])

  return {tags$, addTag$, removeTag$}
}
```
Also see this example: https://github.com/jayrbolton/ff-example-multi-counters/blob/master/index.js

But I will also fix it so that dynamic initialization of nested components can work, so that events on a stream can dynamically create new nested streams in the state, and those nested streams will trigger a snabbdom `patch` call.

**Comment by MangelMaxime** [comment]
Ah yes sorry I was tired 😊. 

Thanks for the sample.
